---
layout: cv
title: Richard Opoku's Resume
---
# Richard Opoku
Data Visualization Specialist, Student.

<div id="webaddress">
<a href="richardopokumcconkie@gmail.com">My Email Address</a>
| <a href="http://www.linkedin.com/in/richardopoku0">My linkedin profile</a>
</div>

## Skills



- Financial Planning
- Program Evaluation
- Data Analysis
- MySQL
- Microsoft Power BI
- Spreadsheet Analysis
- Python



### Projects

- Analyzed historical economic trends through constitutional data comparisons
- Performed a Cost- Benefit Analysis of the Three Gorges Dam in China
- Critiqued the credibility of various electoral system on electoral results across various countries
 


### Education


`April 2021 - Present`

*Brigham Young University - Idaho, Rexburg*

- Major
  - Business Analytics
    
- Minor
  - Economics
   








### Professional Experience

`August 2021 - June 2022`

#### ***Economics Tutor, Brigham Young University- Idaho***
 - Helped students understand complex microeconomics and macroeconomics materials
 - Assisted students with homework, projects, test preparations and other academic tasks
 - Worked with students to help them understand key concepts learned in classroom

`September 2022 - April 2023`

#### ***Data Visualization Specialist, Brigham Young University - Idaho***
  - Created over 30 new accurate data report weekly for the University's Coursedog data warehouse
  - Modified ad hoc visualization that set a reliable novel solution to the university's registration data problems
  - Developed new dashboard that highkighted the Record and Registration's unit health and performance

  `June 2024 - August 2024`
    
#### ***Exchange and Clearance Opps Analyst, Goldman Sachs***
  - Conducted root cause analysis to identify and resolve recurring trade and clearance failures ensuring trade execution success and team efficiency
  - Created an effective daily suspense report to highlight unsettled trades, preventing a financial losses and saving above hundred thousand daily for the firm
  - Created interactive dashboards that measured the extent to which trade transactions and settlements are accurately and efficiently completed. 
  







<!-- ### Footer

Last updated: May 2013 -->